export const regionMap = {
    very_high: [
        'afghanistan',
        'east timor',
        'indonesia',
        'iraq',
        'kyrgyzstan',
        'laos',
        'mongolia',
        'myanmar',
        'north korea',
        'oman',
        'pakistan',
        'philippines',
        'saudi arabia',
        'tajikistan',
        'turkmenistan',
        'uzbekistan',
        'yemen',
    ],
    high: [
        'bahrain',
        'bangladesh',
        'bhutan',
        'brunei',
        'cambodia',
        'china',
        'india',
        'iran',
        'jordan',
        'kuwait',
        'malaysia',
        'nepal',
        'qatar',
        'taiwan',
        'united arab emirates',
        'vietnam',
    ],
    moderate: [
        'sri lanka',
        'thailand',
    ],
    low: [
        'japan',
        'singapore',
        'south korea',
    ],
};